CI fixes

diff --git a/.github/workflows/pay_ad_hoc.yml b/.github/workflows/pay_ad_hoc.yml
--- a/.github/workflows/pay_ad_hoc.yml
+++ b/.github/workflows/pay_ad_hoc.yml
@@ -26,15 +26,19 @@ jobs:
         env:
           ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}
 
-      - name: Validate the payload
-        run: for env_var in ZONE_NUMBER SPACE_NUMBER; 
-             do 
-               if ! echo "${{ github.event.client_payload.data }}" | egrep -q "^$env_var"; 
-               then 
-                 echo "::error Schedule failed; missing '$env_var'"; 
-                 exit 1; 
-               fi; 
-             done
+      - name: Check for zone number
+        run: if [ -z "${{ github.event.client_payload.zone_number }}" ];
+             then
+              echo "::error Please provide a zone_number in client_payload.";
+              exit 1;
+             fi
+
+      - name: Check for space number
+        run: if [ -z "${{ github.event.client_payload.space_number }}" ];
+             then
+              echo "::error Please provide a zone_number in client_payload.";
+              exit 1;
+             fi
 
       - name: Deploy AWS infrastructure
         run: ./docker-compose -f docker-compose.deploy.yml run --rm terraform apply
@@ -42,6 +46,6 @@ jobs:
       - name: Run an ad-hoc parking bot
         if: github.event == 'execute'
         run: ./docker-compose up -d selenium && 
-              zone_number=$(echo ${{ github.event.client_payload.data }} | egrep '^ZONE=' | cut -f2 -d '=') && 
-              space_number=$(echo ${{ github.event.client_payload.data }} | egrep '^SPACE=' | cut -f2 -d '=') && 
+              zone_number=${{ github.event.client_payload.zone_number }} && 
+              space_number=${{ github.event.client_payload.space_number }} && 
               docker-compose run --rm -e ZONE_NUMBER=$zone_number -e SPACE_NUMBER=$space_number parking_bot
