Fix scheduled parking so that it stops blowing up my inbox

diff --git a/.github/workflows/pay_on_a_schedule.yml b/.github/workflows/pay_on_a_schedule.yml
--- a/.github/workflows/pay_on_a_schedule.yml
+++ b/.github/workflows/pay_on_a_schedule.yml
@@ -75,21 +75,32 @@ jobs:
         env:
           ENV_PASSWORD: ${{ secrets.env_file_encryption_key }}
 
-      - name: Check for run file
-        run: ./docker-compose run --rm aws s3 cp s3://${{ secrets.queue_bucket }}/ppprk_run_file
+      - name: Check for and download run file
+        run: ./docker-compose -f docker-compose.deploy.yml run --rm aws s3 cp s3://${{ secrets.queue_bucket }}/ppprk_run_file || true
 
-        # The next few steps should only execute if a scheduled run was found
-        # or if we were told to execute per the 'execute' webhook.
-      - name: Deploy AWS infrastructure
-        run: ./docker-compose -f docker-compose.deploy.yml run --rm terraform apply
+      - name: Stop if run file wasn't downloaded
+        run: if [ ! -f ppprk_run_file ];
+             then
+               echo "::error:No run file found. Halting.";
+               echo "::set-env name=continue_parking::1";
+             fi
 
       - name: Check if current time exceeds desired time to park (if scheduled)
         run: current_time=$(date +%s); 
              desired_time=$(cat ppprk_run_file | 
                 egrep '^TIME_TO_SCHEDULE_PARKING=' | 
                 cut -f2 -d '='); 
-             result=$([ "$current_time" -ge "$desired_time" ]); 
-             echo "::set-env name=continue_parking::$result"
+             if [ "$current_time" -lt "$desired_time" ];
+             then
+               echo "::error We're scheduled to run at $(date -d $desired_time), but it's $(date -d $current_time). Halting until go time.";
+               echo "::set-env name=continue_parking::1";
+             fi
+
+        # The next few steps should only execute if a scheduled run was found
+        # or if we were told to execute per the 'execute' webhook.
+      - name: Deploy AWS infrastructure
+        if: env.continue_parking == 0
+        run: ./docker-compose -f docker-compose.deploy.yml run --rm terraform apply
 
       - name: Run Parking Bot at a scheduled time (if scheduled)
         if: env.continue_parking == 0
